# example GitHub workflow

name: Publish resume in JSONResume format as Github Page

on:
  push:
    branches: [main]

jobs:
  check_run:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  build:
    runs-on: ubuntu-latest
    needs: check_run
    steps:
      - uses: actions/checkout@v3
      - uses: kelvintaywl/action-jsonresume-export@v1
        name: Export resume as HTML
        with:
          theme: jsonresume-theme-kendall
          resume_filepath: resume.json
          # modifies the index.html in-place
          output_filepath: index.html
      - name: Commit published HTML
        id: commit
        run: |
          git config --local user.email "tyler+githubactions@neherdata.com"
          git config --local user.name "Tyler M. Neher"
          if [ -n "$(git status --porcelain docs/index.html)" ]; then
            git add index.html
            git commit -m "[ci skip] chore(index.html): update resume page"
            echo ::set-output name=exit_code::0
          else
            echo ::set-output name=exit_code::1
          fi
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        if: steps.commit.outputs.exit_code == 0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
